language: scala
sudo: false

jobs:
  include:
    - stage: test
      script: sbt ^^1.2.4 test scripted
      jdk: openjdk11

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
